config/routes.rb
RailsStore2::Application.routes.draw do
 

  resources :reviews
  resources :products

  match '/product_search' => 'products#product_search', :as => :product_search 

  root :to => 'products#menu'

end

app/models/googleproductssearch.rb
require 'open-uri'


class Googleproductssearch

  def initialize(query)
  	@query = query
  end

  def search
    file = open("https://www.googleapis.com/shopping/search/v1/public/products?key=AIzaSyBtm1EPiT8NUSsgTJhBb5dxlhGAi8FvLu4&country=US&q=#{URI.escape(@query)}", :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE)
    JSON.load(file.read)
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :in_cart, :name, :price, :product_picture
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating
  belongs_to :product 
end

app/models/twitterproductsearch.rb
require 'open-uri'
require 'json'
require 'uri'


class Twitterproductsearch < Object

  def initialize(query)
  	@query = query
  end

  def search
  	# NOTE THAT THERE IS STILL A BUG HERE. GSUB ERROR WITH THE URI ESCAPE AGAIN
    file = open("http://search.twitter.com/search.json?q=#{URI.escape(@query)}")
    @results = JSON.load(file.read)
  end

end


 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  



# #****************INTEGRATING THE TWITTER API**********************
# get '/products/search' do
#   @q = params[:q]
#   file = open("http://search.twitter.com/search.json?q=#{URI.escape(@q)}")
#   @results = JSON.load(file.read)
#   erb :search_results
# end
# #*****************************************************************
# # WTF why did just moving this code block from the bottom to up here make it work??


# #***************INTEGRATING THE GOOGLE PRODUCTS API***************
# get '/products/search_google' do 
#   @q = params[:q]
#   file = open("https://www.googleapis.com/shopping/search/v1/public/products?key=AIzaSyBtm1EPiT8NUSsgTJhBb5dxlhGAi8FvLu4&country=US&q=#{URI.escape(@q)}", :ssl_verify_mode => OpenSSL::SSL::VERIFY_NONE)
#   @results = JSON.load(file.read)
#   erb :search_google
# end
# #*****************************************************************

  def product_search
    @q = params[:product_search_name]
    @results = Googleproductssearch.new(@q).search
  end

  def menu
  end

  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @review = Review.where(:product_id => params[:id])
    @products = Product.all

    @results = Twitterproductsearch.new(@product.name).search

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Cart successfully updated!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
    @product = Product.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
#**********INPUTTING SOME SHIT HERE
    if params[:product_id]
    @product = Product.find(params[:product_id])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStore2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_cart.html.erb
<head>
  <%= stylesheet_link_tag 'products' %>
</head>

<h3> Items in wishlist: </h3>

<% total = 0 %>
<% @products.each do |f| %>

  <% if f.in_cart == true %>
    
    <div class="cart_item_name"> - <%= f.name.capitalize %></div> 
    <div class="cart_item_price"> Price: <%= number_to_currency(f.price) %> </div>
    
    <div class="cart_remove_button">
      <%= form_tag(product_path(f), :method => "put") do %>
        <input type='hidden' value="false" name='product[in_cart]'/>
        <button type="submit">Remove from wishlist</button> 
      <% end %>
    </div>
    <% total = total + f.price %>

  <% end %>
<% end %>

<p class="cart_total">Total: <%= number_to_currency(total) %></p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :product_picture %><br />
    <%= f.text_field :product_picture %>
  </div>
  <div class="field">
    <%= f.label :in_cart %><br />
    <%= f.check_box :in_cart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'See all products', products_path %>

app/views/products/index.html.erb
<head>
  <%= stylesheet_link_tag 'products' %>
</head>

<h1 class="index_title">Products in database:</h1>


<div class="index_all_products">

<% @products.each do |product| %>

<div id="index_one_whole_product">
  
  <p class="index_product_id">  
    <%= product.id %>

  <div class="index_product_image">
    <img src="<%= product.product_picture %>" width="240" height=auto></div></p>

  <p class="index_product_name">
    <%= product.name.capitalize %></p>

  <p class="index_price">
    <%= number_to_currency(product.price) %></p>

  <p class="index_product_cart_button">
    <% if product.in_cart %>
      <%= form_tag(product_path(product), :method => "put") do %>
        <input type='hidden' value="false" name='product[in_cart]'/>
        <button type="submit">Remove from wishlist</button> 
      <% end %>
    <% else %>
      <%= form_tag(product_path(product), :method => "put") do %>
        <input type='hidden' value="true" name='product[in_cart]'/>
        <button type="submit">Add to wishlist</button> 
      <% end %>
    <% end %></p>

  <p class="index_product_links">
    <%= link_to 'Detail', product %>
    <%= link_to 'Edit', edit_product_path(product) %>
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<% end %>
</div>

<br />

<div class="index_new_product_search">
  <form action='/product_search' method='get'>
    <label for='product_search_name'>Search for new product</label>
    <input type='text' name='product_search_name'/>

    <button>Search</button>
  </form></div>

<div class="index_cart">
  <%= render 'cart' %></div>

app/views/products/menu.html.erb
<head>
  <%= stylesheet_link_tag 'products' %>
</head>


<body>

  <h1 class="menu_title">Welcome to Bob's Wishlist</h1>

  <form class="menu_search_field" action='/product_search' method='get'>
    <p class="menu_words"><label for='product_search_name'>Lets go find some shit!</label></p>
    <p>
    <input type='text' name='product_search_name'/>
    <button>Search!</button>
</p>
  </form>

<div class="menu_links">
  <%= link_to 'See all products', products_path %>
  <%= link_to 'See all reviews', reviews_path %>
</div>

</body>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'See all products', products_path %>

app/views/products/product_search.html.erb
<h1> Search results for <%= @q %> on Google Products </h1>


<%= @results["items"].each do |result| %>

<div>
  <img src=<%= result["product"]["images"][0]["link"] %> width="240" height=auto>
  <p> <%= result["product"]["title"] %> </p>
  <p> <%= number_to_currency(result["product"]["inventories"][0]["price"]) %> </p>
  <p> <%= result["product"]["description"] %> </p>
  <p> <a href=<%= result["product"]["link"] %>>More product details</a> </p>

   <%= form_tag(products_path, :method => "post") do %>
     <input type='hidden' value="<%= result["product"]["title"] %>" name='product[name]'/>
     <input type='hidden' value="<%= result["product"]["inventories"][0]["price"] %>" name='product[price]'/>
     <input type='hidden' value="<%= result["product"]["description"] %>" name='product[description]'/>
     <input type='hidden' value="<%= result["product"]["images"][0]["link"] %>" name='product[product_picture]'/>
     <input type='hidden' value="true" name='product[in_cart]'/>
     <button type="submit">Add to Eu-wen's wishlist</button> 
   <% end %>

</div>

<% end %>

app/views/products/show.html.erb
<head>
  <%= stylesheet_link_tag 'products' %>
</head>


<div class="show_all_text">
<p id="notice"><%= notice %></p>

<p class="show_image">
  <img src="<%= @product.product_picture %>" width="240" height=auto>
</p>

<p>
  <b>ID:</b>
  <%= @product.id %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Existing reviews:</b>
  <% @review.each do |a_review| %>
  <p>Review ID: <%= a_review.id %></p>
  <p>    <%= a_review.body %></p>
  <% end %>
</p>


  <form action='/reviews/new' method='get'>
  <input type='hidden' value="<%= @product.id %>" name='product_id'/>
  <button type="submit">Write a review for <%= @product.name %></button> 
  </form>

<% if @product.in_cart %>
  <%= form_tag(product_path(@product), :method => "put") do %>
  <input type='hidden' value="false" name='product[in_cart]'/>
  <button type="submit">Remove from wishlist</button> 
  <% end %>
<% else %>
  <%= form_tag(product_path(@product), :method => "put") do %>
  <input type='hidden' value="true" name='product[in_cart]'/>
  <button type="submit">Add to wishlist</button> 
  <% end %>
<% end %>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'See all products', products_path %>


<h3> What people are tweeting about <%= @product.name %></h3>

<% @results["results"].each do |result| %>
  <div>
    <img src="<%= result["profile_image_url"] %>">
    <p>Username: <%= result["from_user"] %>, <%= result["from_user_name"] %></p>
    <p><%= result["created_at"] %></p>
    <p><%= result["text"] %></p>
  </div>
<% end %>
</div>

<div class="show_cart">
  <%= render 'cart' %></div>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div>Rating:
    <%= f.radio_button(:rating, 1) %>
    <%= f.label(:rating_one, "One (poor)") %>
    <%= f.radio_button(:rating, 2) %>
    <%= f.label(:rating_two, "Two") %>
    <%= f.radio_button(:rating, 3) %>
    <%= f.label(:rating_three, "Three") %>
    <%= f.radio_button(:rating, 4) %>
    <%= f.label(:rating_four, "Four") %>
    <%= f.radio_button(:rating, 5) %>
    <%= f.label(:rating_five, "Five (excellent)") %>
  </div>
  <div class="field">
    <% if @product %>
    <input type="hidden" name='review[product_id]' value='<%= @product.id %>'>
    <% else %>
    <select name="review[product_id]">
      <% Product.all.each do |doit| %>
      <option value="<%= doit.id %>">
        <%= doit.name %>
      </option>
      <% end %>
    <!--<%= f.label :product_id %><br />
    <%= f.number_field :product_id %>  changed some shit here, from f.number_field :product_id to @product.id -->
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Review ID</th>
    <th>Body</th>
    <th>Rating</th>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.id %></td>
    <td><%= review.body %></td>
    <td><%= review.rating %></td>
    <td><%= review.product.name if review.product %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>
<%= link_to 'See all products', products_path %>

app/views/reviews/new.html.erb
<% if @product %>
<h1>New review for product <%= @product.name %></h1>
<% else %>
<h1>New review for product</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @review.body %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Product:</b>
  <%= @review.product_id %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>